In [1]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException
import pandas as pd
import numpy as np
import time

In [63]:
#PATIENCE_TIME = 60
#LOAD_MORE_BUTTON_XPATH = '//*[@id="browse-itemsprimary"]/li[2]/button/span/span[2]' 

#driver = webdriver.Chrome('./chromedriver.exe')
#driver.get(YOUTUBER_HOME_PAGE_URL)
driver = webdriver.Chrome(r'chromedriver.exe')
driver.get('https://www.exportersindia.com/search.php?srch_catg_ty=prod&term=LED&cont=IN&ss_status=N')
while True:
    try:
        loadMoreButton = driver.find_element_by_xpath("//a[contains(@class,'dib p7px w170px bgfff gray ttu bdr darkbdr1 br5px')]")
        time.sleep(2)
        loadMoreButton.click()
        time.sleep(5)
    except Exception as e:
        print (e)
        break
print ("Complete")
time.sleep(10)
#driver.quit()

Message: element click intercepted: Element <a onclick="add_more_product_classified();$('#load_more_a_id').hide();" class="dib p7px w170px bgfff gray ttu bdr darkbdr1 br5px" id="load_more_a_id" style="display: inline-block;">...</a> is not clickable at point (600, 20). Other element would receive the click: <span style="font-size:12px;">...</span>
  (Session info: chrome=108.0.5359.99)
Stacktrace:
Backtrace:
	Ordinal0 [0x0051ACD3+2075859]
	Ordinal0 [0x004AEE61+1633889]
	Ordinal0 [0x003AB7BD+571325]
	Ordinal0 [0x003E1499+791705]
	Ordinal0 [0x003DF4AC+783532]
	Ordinal0 [0x003DD0AB+774315]
	Ordinal0 [0x003DBD37+769335]
	Ordinal0 [0x003D1C76+728182]
	Ordinal0 [0x003F731C+881436]
	Ordinal0 [0x003D15BF+726463]
	Ordinal0 [0x003F7534+881972]
	Ordinal0 [0x0040B56A+963946]
	Ordinal0 [0x003F7136+880950]
	Ordinal0 [0x003CFEFD+720637]
	Ordinal0 [0x003D0F3F+724799]
	GetHandleVerifier [0x007CEED2+2769538]
	GetHandleVerifier [0x007C0D95+2711877]
	GetHandleVerifier [0x005AA03A+521194]
	GetHandleVerifier [0x005A8DA0+516432]
	Ordinal0 [0x004B682C+1665068]
	Ordinal0 [0x004BB128+1683752]
	Ordinal0 [0x004BB215+1683989]
	Ordinal0 [0x004C6484+1729668]
	BaseThreadInitThunk [0x7721FEF9+25]
	RtlGetAppContainerNamedObjectPath [0x778D7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x778D7B8E+238]

Complete

In [64]:
lists = []

for i in range (1,2):
    name = driver.find_elements(By.XPATH, '//p[@class="mb5px ffos xlarge graydark b dib"]')
    no = driver.find_elements(By.XPATH, '//a[contains(@class,"view_mobile number") or contains(@class,"view_mobile")]')
    ad = driver.find_elements(By.XPATH, '//span[@class="black title_tooltip"]')
    #//td[contains(@class,'blob-code-addition') or contains(@class,'blob-code-deletion')]
    #no = driver.find_elements(By.XPATH, "//a[contans(@class, 'view_mobile number') or contains(@class, 'view_mobile')]")
    
    for i in range(len(name)):
        lists.append([name[i].text, no[i].text, ad[i].text])
        
    time.sleep(10)

In [66]:
data = pd.DataFrame(lists, columns = ['Name', 'Number', 'Address'])

In [54]:
#data

,Name,Number,Address
0,Dev Digital Electronics,08048781528,"Sector 25, Gandhinagar, Gujarat, India"
1,Vedaaanshi Safety And Sign,08047015541,"Nanpura, Surat, Gujarat, India"
2,Skytech Exports Private Limited,08047015332,"Sirsi Road, Jaipur, Rajasthan, India"
3,MAA GAYATRI ENTERPRISES,08047017559,"NIT, Faridabad, Haryana, India"
4,Vishwakarma Industries,08047016763,"Falna, Pali, Rajasthan, India"
...,...,...,...
9547,Monalisa Fountains,View Mobile,"Azad Chowk, Raipur, Chhattisgarh, India"
9548,LiPo Technology Private Limited,08048781949,"Haveli Chowk, Botad, Gujarat, India"
9549,Focusun Energy Systems,08048788528,"Avinashi Road, Coimbatore, Tamil Nadu, India"
9550,Maa Laxmi Enterprises,08047025908,"Dhawadwadi, Pune, Maharashtra, India"
9551,BANDHAN ENTERPRISES,08048800170,"Vikas Puri, Delhi, India"

In [67]:
data.to_excel("ExporterIndiaData.xlsx")